### PR TITLE
Initial Pack Transfer

### PR DESCRIPTION
**Pull request by LindsayHill**
Initial transfer of code from @paul-mulvihill 

To do:

- [x] Fix remaining linting errors (primarily line length now)
- [x] Fill in details for README
- [x] Write an example `cisco_aci.yaml.example`, and make sure it passes validation

@paul-mulvihill can you complete those?

### CODE REVIEW

**Comment by paul-mulvihill** [comment]
Hi @LindsayHill  yeah i can take care of those. It was on my list to do, I just made the PR to try leverage toe ci checks to show me was was wrong.  
Should I still work on my fork based out of the incubator repo or do i now need to switch over to using this repo?

**Comment by LindsayHill** [comment]
Switch over to editing this branch on this repo. I've given you access so you should be able to.

CI checks don't run properly against exchange-incubator PRs for a variety of reasons (not just because they're not set up, but also because people submit PRs in different ways, with actions dirs sometimes at top level, sometimes further down).

I should probably at least try to run basic linting.

**Comment by paul-mulvihill** [comment]
@LindsayHill ok will switch over tomorrow (end of my day here) when I carry on working on this..

**Comment by LindsayHill** [comment]
No rush, take your time - you should now have the access you need.

One minor thing here: I am using this as a test case for migrating from CircleCI 1.0 -> 2.0. At this stage it should be running all tests correctly, but if you see something where it doesn't seem to be having properly with tests, ping me.

**Comment by paul-mulvihill** [comment]
Hi @LindsayHill just doing some final checks to make sure i've not missed anything.. any comments or requests beyond the ones above before I say it's good for merge?
do you want me to merge or get you guys to when I'm happy?

**Comment by LindsayHill** [comment]
@paul-mulvihill I made some language changes to the README. Looks like it should be OK to merge now.

**Comment by LindsayHill** [comment]
You can go ahead and merge it if you're happy

**Comment by paul-mulvihill** [comment]
@LindsayHill cool thanks.. i'll get this merged then do another PR if i need to make an adjustments.

**Pull request merged**
